import assert from 'node:assert/strict';
const base='http://localhost:3000';let cookie='';async function req(path,options={}){const r=await fetch(base+path,{...options,headers:{Origin:base,Cookie:cookie,...options.headers}});for(const c of r.headers.getSetCookie())if(c.startsWith('sw-session='))cookie=c.split(';')[0];return r;}
await req('/api/state');
const text='Die Ersatzhandtücher befinden sich im linken Schrank im Wirtschaftsraum.';let f=new FormData();f.set('file',new File([text],'synthetische-gaestemappe.txt',{type:'text/plain'}));let r=await req('/api/upload',{method:'POST',body:f});assert.equal(r.status,200);let d=await r.json();assert.equal(d.text,text);const attachment=d.attachment;
r=await req('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'contribute',title:'Lagerort der Handtücher',body:text,unit:'Alle Wohnungen',attachment})});d=await r.json();assert.equal(r.status,200);const c=d.state.contributions[0];r=await req('/api/upload?id='+attachment.id);assert.equal(r.status,200);assert.equal(await r.text(),text);await req('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'review',id:c.id,title:c.title,body:c.body,approve:true})});r=await req('/api/state');d=await r.json();assert.ok(d.state.entries.some(e=>e.attachments?.some(a=>a.id===attachment.id)));
// Minimal, valid one-page synthetic PDF to exercise actual text extraction.
const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const stream='BT /F1 16 Tf 50 700 Td (Synthetic FAQ: Fresh towels are in the left cupboard.) Tj ET';objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;f=new FormData();f.set('file',new File([pdf],'synthetic-faq.pdf',{type:'application/pdf'}));r=await req('/api/upload',{method:'POST',body:f});d=await r.json();assert.equal(r.status,200);assert.ok(d.text.includes('Fresh towels'),JSON.stringify(d));
f=new FormData();f.set('file',new File(['no'],'script.exe',{type:'application/octet-stream'}));r=await req('/api/upload',{method:'POST',body:f});assert.equal(r.status,400);
const other=await fetch(base+'/api/upload?id='+attachment.id);assert.equal(other.status,404);
console.log('PASS: TXT- und PDF-Extraktion, persistenter privater Download, Anhang an veröffentlichtem Wissen, Format- und Fremdzugriffsschutz.');
