import type {Process,State} from '../types';
import type {FloorPlan,Room,Pin,SpatialState} from './types';
const W=460,H=660;
const poly=(pts:number[][])=>pts.map(([x,y])=>[+(x/W).toFixed(4),+(y/H).toFixed(4)] as [number,number]);
const pt=(x:number,y:number)=>({x:+(x/W).toFixed(4),y:+(y/H).toFixed(4)});
const geometry=`<path class="sp-connector" d="M146 214V233H182V214ZM293 214V233H328V214Z"/>
<g class="sp-furniture"><rect x="55" y="62" width="113" height="113" rx="4"/><rect x="62" y="69" width="45" height="29" rx="5"/><rect x="115" y="69" width="45" height="29" rx="5"/><rect x="289" y="66" width="90" height="109" rx="4"/><rect x="296" y="73" width="33" height="27" rx="5"/><rect x="337" y="73" width="33" height="27" rx="5"/><rect x="61" y="281" width="25" height="124" rx="2"/><rect x="61" y="392" width="45" height="17" rx="2"/><rect x="211" y="321" width="91" height="25" rx="3"/><ellipse cx="255" cy="334" rx="22" ry="7"/><rect x="143" y="321" width="27" height="12" rx="3"/><ellipse cx="156.5" cy="347" rx="12" ry="16"/><rect x="280" y="356" width="30" height="28" rx="3"/><rect x="343" y="312" width="46" height="15" rx="2"/><rect x="59" y="495" width="30" height="95" rx="5"/><rect x="59" y="589" width="112" height="27" rx="5"/><rect x="94" y="510" width="94" height="73" rx="10"/><ellipse cx="274" cy="531" rx="37" ry="30"/><rect x="258" y="488" width="30" height="10" rx="4"/><rect x="258" y="564" width="30" height="10" rx="4"/><rect x="222" y="515" width="11" height="27" rx="4"/><rect x="314" y="515" width="11" height="27" rx="4"/></g>
<g class="sp-furniture-line"><path d="M55 107H168M289 110H379M69 309H80M69 356H80M273 324V330M258 331V336M169 322V332M63 534H84M63 566H84M100 593V613M132 593V613"/><rect x="68" y="287" width="11" height="15" rx="2"/><path d="M284 360L306 380M306 360L284 380"/></g>
<g class="sp-door-gap"><path d="M146 214H182M293 214H328M146 233H182M293 233H328M119 247V278M176 314H208M65 452H105M438 372V399"/></g>
<g class="sp-door"><path d="M146 214V181A33 33 0 0 1 179 214M293 214V181A33 33 0 0 1 326 214M119 247H150A31 31 0 0 1 119 278M176 314V347A33 33 0 0 0 209 314M65 452V485A33 33 0 0 0 98 452"/></g>
<g class="sp-window-line"><path d="M49 23H120M305 23H378M33 89V151M105 628H150M273 641H319"/></g>`;
const plan:FloorPlan={id:'fp-alpenblick',unit:'Alpenblick',title:'Alpenblick · Grundriss',width:W,height:H,geometry};
const rooms:Room[]=[
{id:'r-bed1',floorPlanId:plan.id,name:'Schlafzimmer 1',tone:'bed',polygon:poly([[32,22],[144,22],[144,30],[204,30],[204,193],[190,193],[190,214],[32,214]]),label:{x:.255,y:.07}},
{id:'r-bed2',floorPlanId:plan.id,name:'Schlafzimmer 2',tone:'bed',polygon:poly([[258,22],[399,22],[399,65],[423,65],[423,200],[405,200],[405,214],[278,214],[278,128],[258,128]]),label:{x:.73,y:.07}},
{id:'r-hall',floorPlanId:plan.id,name:'Flur',tone:'living',polygon:poly([[119,233],[363,233],[363,302],[421,302],[421,360],[438,360],[438,406],[342,406],[342,351],[321,351],[321,307],[119,307]]),label:{x:.85,y:.56}},
{id:'r-kitchen',floorPlanId:plan.id,name:'Küche',tone:'service',polygon:poly([[53,233],[119,233],[119,429],[164,429],[164,452],[53,452]]),label:{x:.187,y:.395}},
{id:'r-bath',floorPlanId:plan.id,name:'Bad',tone:'service',polygon:poly([[134,314],[320,314],[320,393],[159,393],[159,382],[134,382]]),label:{x:.49,y:.57}},
{id:'r-living',floorPlanId:plan.id,name:'Wohnzimmer',tone:'living',polygon:poly([[53,452],[202,452],[202,469],[258,469],[258,452],[354,452],[354,626],[335,626],[335,641],[160,641],[160,627],[32,627],[32,501],[53,501]]),label:{x:.48,y:.91}}];
type Def=[string,string,string,number,[string,string,string?][]];
const defs:Def[]=[
['sp-bett','Bett frisch beziehen','Bett für die nächsten Gäste vorbereiten.',6,[['Bett abziehen','Bettwäsche und Bezüge vollständig abziehen und in den grauen Wäschesack geben.','Benutzte Wäsche nicht auf den Boden legen.'],['Matratze kontrollieren','Matratze und Topper auf Flecken, Feuchtigkeit und Schäden prüfen. Auffälligkeiten fotografieren und melden.'],['Frisch beziehen','Spannbettlaken glatt ziehen, Decken und Kissen mit frischer Wäsche beziehen. Verschlüsse nach unten.'],['Für die Anreise vorbereiten','Decke zurückschlagen, Kissen aufschütteln, Bett glatt streichen und den Nachttisch abwischen.']]],
['sp-matratze','Matratze kontrollieren','Kurzer Check zwischen zwei Belegungen.',2,[['Oberfläche prüfen','Matratzenschoner abnehmen und die Oberfläche auf Flecken und Feuchtigkeit prüfen.'],['Auffälligkeiten melden','Schäden oder Flecken mit Foto über „Problem melden“ an die Betreiberin geben.']]],
['sp-decke','Zusatzdecke bereitlegen','Für kühle Nächte oder Gästewunsch.',1,[['Decke prüfen','Zusatzdecke aus dem Schrank nehmen und auf Sauberkeit und Geruch prüfen.'],['Decke bereitlegen','Decke gefaltet am Fußende des Bettes ablegen.']]],
['sp-arbeitsflaeche','Arbeitsfläche reinigen','Küchenzeile hygienisch sauber machen.',4,[['Fläche freiräumen','Alle Gegenstände von der Arbeitsfläche nehmen und Geschirr in die Spüle stellen.'],['Krümel entfernen','Krümel und lose Reste mit dem Handbesen in den Restmüll fegen.'],['Fläche reinigen','Mit dem Küchenreiniger und dem blauen Küchentuch die Fläche abwischen.','Nur das blaue Küchentuch verwenden, nie ein Badtuch.'],['Trocken nachwischen','Mit einem trockenen Tuch nachwischen, damit keine Streifen bleiben.']]],
['sp-kueche','Küchenausstattung prüfen','Vollständigkeit vor der Anreise.',3,[['Geschirr prüfen','Teller, Gläser und Besteck laut Inventarliste zählen und auf Schäden prüfen.'],['Geräte prüfen','Kaffeemaschine, Wasserkocher und Herd kurz einschalten und Funktion prüfen.','Keine Geräte öffnen; Defekte nur melden.'],['Fehlendes melden','Fehlende oder defekte Teile über „Problem melden“ an die Betreiberin geben.']]],
['sp-kaffee','Kaffee & Tee auffüllen','Willkommensvorrat ergänzen.',2,[['Bestand prüfen','Kapseln, Teebeutel und Zucker im Vorratskorb zählen.'],['Vorräte auffüllen','Aus dem Wirtschaftsraum auf je sechs Kapseln und sechs Teebeutel auffüllen.'],['Ordentlich anrichten','Korb sauber wischen und sichtbar neben der Kaffeemaschine platzieren.']]],
['sp-waschbecken','Waschbecken reinigen','Becken und Armatur streifenfrei.',3,[['Tuch vorbereiten','Lege ein frisches Tuch bereit, das nur für das Waschbecken verwendet wird.','Eigene Tücher für Waschbecken und Toilette verwenden.'],['Becken reinigen','Reinige das Becken mit dem Badreiniger und spüle anschließend mit klarem Wasser nach.'],['Armatur polieren','Wische die Armatur ab und poliere sie mit einem trockenen, sauberen Tuch.'],['Ergebnis prüfen','Prüfe Becken und Armatur auf Rückstände. Lege das verwendete Tuch zur Wäsche.']]],
['sp-seife','Seife nachfüllen','Spender am Waschbecken.',1,[['Füllstand prüfen','Seifenspender anheben und Füllstand prüfen.'],['Seife nachfüllen','Bei weniger als der Hälfte aus dem Kanister im Wirtschaftsraum nachfüllen.'],['Spender abwischen','Spender außen abwischen und zurückstellen.']]],
['sp-armatur','Armatur prüfen','Wasser und Abfluss kontrollieren.',2,[['Wasser öffnen','Warm- und Kaltwasser kurz laufen lassen und auf Druck und Temperatur achten.'],['Abfluss prüfen','Abfluss beobachten: läuft das Wasser zügig ab? Sieb bei Bedarf reinigen.'],['Auffälligkeiten melden','Tropfen, Kalk oder langsamen Abfluss an die Betreiberin melden.']]],
['sp-toilette','Toilette reinigen','Hygienisch und sicher.',5,[['Eigenes Tuch bereitlegen','Handschuhe anziehen und das rote Toilettentuch bereitlegen.','Das rote Tuch nie für Waschbecken oder Dusche verwenden.'],['Reiniger anwenden','WC-Reiniger unter den Rand geben und einige Minuten einwirken lassen.','Reinigungsmittel nicht mischen.'],['Außenflächen reinigen','Deckel, Brille und Außenseite mit dem roten Tuch abwischen; innen mit der Bürste reinigen und spülen.'],['Ergebnis prüfen','Sichtkontrolle, Deckel schließen, Handschuhe ausziehen und Hände waschen.']]],
['sp-verbrauch','Verbrauchsmaterial auffüllen','Papier und Hygieneartikel.',1,[['Bestand prüfen','Toilettenpapier und Hygienebeutel im Bad zählen.'],['Papier auffüllen','Auf zwei volle Rollen plus Reserve auffüllen; Reserve sichtbar im Regal.']]],
['sp-gaestemappe','Gästemappe vorbereiten','Alle Informationen vollständig.',2,[['Vollständigkeit prüfen','Gästemappe öffnen und prüfen, ob WLAN-Blatt, Hausordnung und Notfallnummern enthalten sind.'],['Informationen prüfen','Kontrollieren, ob die Angaben aktuell sind; veraltete Blätter melden.','Keine persönlichen Gästedaten in die Mappe legen.'],['Mappe bereitlegen','Mappe geschlossen mittig auf den Wohnzimmertisch legen.']]],
['sp-wohnbereich','Wohnbereich vorbereiten','Der erste Eindruck bei der Anreise.',4,[['Lüften','Fenster fünf Minuten weit öffnen.'],['Oberflächen prüfen','Tisch, Regale und Fensterbänke abwischen.'],['Sitzbereich herrichten','Kissen aufschütteln, Decke falten, Fernbedienungen auf den Tisch legen.'],['Raum kontrollieren','Fenster schließen, Licht aus, letzter Blick auf den Gesamteindruck.']]]];
const pins:Pin[]=[
{id:'pin-bed1',floorPlanId:plan.id,roomId:'r-bed1',number:1,name:'Doppelbett',...pt(117,139),processIds:['sp-bett','sp-matratze']},
{id:'pin-bed2',floorPlanId:plan.id,roomId:'r-bed2',number:2,name:'Gästebett',...pt(335,140),processIds:['sp-bett','sp-decke']},
{id:'pin-kitchen',floorPlanId:plan.id,roomId:'r-kitchen',number:3,name:'Arbeitsfläche',...pt(85,353),processIds:['sp-arbeitsflaeche','sp-kueche','sp-kaffee']},
{id:'pin-sink',floorPlanId:plan.id,roomId:'r-bath',number:4,name:'Waschbecken',...pt(258,337),processIds:['sp-waschbecken','sp-seife','sp-armatur']},
{id:'pin-toilet',floorPlanId:plan.id,roomId:'r-bath',number:5,name:'Toilette',...pt(157,354),processIds:['sp-toilette','sp-verbrauch']},
{id:'pin-living',floorPlanId:plan.id,roomId:'r-living',number:6,name:'Gästemappe',...pt(278,538),processIds:['sp-gaestemappe','sp-wohnbereich']}];
export function spatialProcesses():Process[]{return defs.map(([id,title,description,minutes,steps])=>({id,title,description,category:'Vor Ort',roles:['owner','staff','cleaner'],minutes,version:1,steps:steps.map(([t,body,caution],i)=>({id:`${id}-s${i}`,title:t,body,caution,entryIds:[]}))}));}
export function spatialSeed():SpatialState&{processes:Process[]}{return {floorPlans:[structuredClone(plan)],rooms:structuredClone(rooms),pins:structuredClone(pins),guidance:[],feedback:[],processes:spatialProcesses()};}
export function ensureSpatial(s:State){const d=spatialSeed();for(const k of ['floorPlans','rooms','pins','guidance','feedback'] as const)if(!Array.isArray(s[k]))(s as any)[k]=d[k];for(const p of d.processes)if(!s.processes.some(x=>x.id===p.id))s.processes.push(p);}
