import {State,Entry,Process,Role,Standard} from './types';
export function seed():State {
const today=new Date().toISOString().slice(0,10); const all:Role[]=['owner','staff','cleaner'];
const content=[
['Wäsche für den Gästewechsel','Housekeeping','Alle Wohnungen','Pro gebuchter Person ein großes und ein kleines Handtuch bereitlegen. Bettwäsche vollständig wechseln. Saubere Wäsche liegt im beschrifteten Schrank im Wirtschaftsraum. Benutzte Wäsche kommt in den grauen Sack.'],
['Schlüsselübergabe Alpenblick','Anreise','Alpenblick','Die Schlüsselübergabe erfolgt persönlich durch Lena. Bei später Anreise Lena kontaktieren und den vereinbarten Ablauf bestätigen lassen. Zugangscodes stehen aus Sicherheitsgründen nicht in dieser Demo.'],
['Schlüsselübergabe Zirbennest','Anreise','Zirbennest','Die betreibende Person übergibt den Schlüssel am Haupteingang. Vor Anreise Ankunftszeit und erreichbare Ansprechperson bestätigen.'],
['Schlüsselübergabe Talruhe','Anreise','Talruhe','Schlüssel bei der vereinbarten Übergabe im Büro abholen. Bei abweichender Ankunft Lena kontaktieren.'],
['Kaffeemaschine im Zirbennest','Housekeeping','Zirbennest','Die Kapselmaschine ausschalten und abkühlen lassen. Kapselbehälter leeren, Tropfschale reinigen und Wassertank mit frischem Wasser füllen. Keine Entkalkung ohne die Geräteanleitung starten.'],
['Bad und Oberflächen','Housekeeping','Alle Wohnungen','Reinigungsmittel ausschließlich nach Etikett verwenden, nicht mischen. Separate Tücher für Bad und Küche verwenden. Armaturen trocknen und Spiegel auf Streifen prüfen.'],
['Fenstergriff im Alpenblick','Technik','Alpenblick','Der Fenstergriff im Schlafzimmer hakt. Nicht mit Gewalt drehen. Bei Problemen Fenster sichern, sofern gefahrlos möglich, und Lena informieren. Eine Reparatur ist bereits angefragt.'],
['Fundgegenstände','Housekeeping','Alle Wohnungen','Fundsachen beschriften: Wohnung, Funddatum und Fundort. Im verschlossenen Fach im Büro abgeben und die Betreiberin informieren. Keine Fotos persönlicher Dokumente hochladen.'],
['Schaden oder Störung melden','Technik','Alle Wohnungen','Wohnung, betroffenes Gerät und beobachtetes Problem notieren, wenn sicher möglich ein Foto aufnehmen. Lena über den betrieblich vereinbarten Kontaktweg informieren. Keine elektrischen Geräte öffnen.'],
['Akute Gefahr','Technik','Alle Wohnungen','Bei akuter Gefahr Arbeiten abbrechen, sich und andere in Sicherheit bringen und den örtlichen Notruf verständigen. Keine eigene Reparatur versuchen. Anschließend Betreiberin informieren, sobald dies sicher möglich ist.'],
['WLAN in Talruhe','Technik','Talruhe','Die WLAN-Informationen befinden sich in der physischen Gästemappe. Bei Verbindungsproblemen zuerst prüfen, ob mehrere Geräte betroffen sind. Router nicht eigenständig zurücksetzen; Lena informieren.'],
['Anreise vorbereiten','Anreise','Alle Wohnungen','Bestätigte Ankunftszeit und Personenzahl prüfen. Reinigungsabschluss bestätigen lassen. Schlüsselübergabe passend zur Wohnung organisieren. Keine persönlichen Gästedaten beim Wissnsepp eingeben.'],
['Anzahlung und Restzahlung','Verwaltung','Alle Wohnungen','Für diesen fiktiven Betrieb gilt: Den vereinbarten Zahlungsplan in der Buchungsbestätigung prüfen. Zahlungseingänge im Buchungssystem abgleichen. Abweichungen an Lena geben. Der Wissnsepp führt keine Zahlungen aus.'],
['Gästekarte ausstellen','Verwaltung','Alle Wohnungen','Das zuständige regionale Gästekartenportal und dessen aktuelle Anleitung verwenden. Berechtigung und erforderliche Angaben dort prüfen. Diese Demo kennt keine verbindlichen regionalen Ausstellungsregeln.'],
['Saisonstart: Material prüfen','Saison','Alle Wohnungen','Bettwäsche, Handtücher und freigegebene Reinigungsmittel zählen. Fehlendes Material melden. Inventar und bekannte Schäden mit der letzten Übergabe abgleichen.'],
['Kontakt und Zuständigkeit','Anreise','Alle Wohnungen','Lena ist für Freigaben, Anreise und technische Eskalation zuständig. Jonas koordiniert Gästewechsel, Mira übernimmt Reinigung. Dies sind fiktive Personen; echte Kontaktdaten sind noch zu hinterlegen.'],
['Farbsystem für Reinigungstücher','Housekeeping','Alle Wohnungen','Blau für Schlafzimmer, Wohn- und Essbereich, Türen, Lichtschalter und Fensterbänke. Grün für Küche, Arbeitsflächen, Spüle und Küchenutensilien. Gelb für Dusche, Waschbecken, Spiegel und den übrigen Badbereich. Rot für WC und den unmittelbaren Bereich darum. Rote oder gelbe Tücher niemals in der Küche, grüne niemals für WC oder Dusche. Für Bad-WC und separates WC jeweils ein frisches rotes Tuch. Die Farbe gilt auch für Moppbezüge, Eimer und Bürsten.'],
['Zehn Arbeitsregeln für die Reinigung','Housekeeping','Alle Wohnungen','Spülmaschine sofort starten, ihre Laufzeit wird genutzt. Früh eine Sammelrunde machen: Wäsche, Müll und Geschirr raus. Waschmaschine früh starten. Von oben nach unten reinigen. Erst trocken, dann feucht. Böden zuletzt. Von den hinteren Räumen zum Ausgang arbeiten. Küche und Sanitärbereiche strikt trennen. Jede Abweichung sofort melden und nichts selbst verdecken. Keine Reinigungsmittel mischen.'],
['Materialstation und Tuchwechsel','Housekeeping','Alle Wohnungen','Die Materialstation ist in vier gekennzeichnete Bereiche geteilt: Blau für Wohnen und Schlafen, Grün für Küche, Gelb für Bad, Rot für WC. Gebrauchte Tücher kommen sofort in den vorgesehenen Wäschesack und niemals zurück in die saubere Materialbox. Heruntergefallene, stark verschmutzte oder riechende Tücher sofort wechseln. Zwischen zwei Wohnungen frische Tücher und Moppbezüge verwenden. Saubere und gebrauchte Materialien getrennt transportieren.'],
['Wann eine Wohnung fertig ist','Housekeeping','Alle Wohnungen','Die Wohnung ist erst fertig, wenn sie sauber, trocken, vollständig, geruchsfrei, funktionsfähig und gastbereit ist. Sichtbar sauber heißt: keine Haare, Krümel, Staubflächen, vermeidbaren Flecken, klebrigen Rückstände, Kalk- oder Wasserreste und keine unangenehmen Gerüche. Vollständig heißt: Betten bezogen, Handtücher, Toilettenpapier und Handseife vorhanden, Küche vollständig, Außenausstattung vollständig. Funktionsfähig heißt: Fenster und Türen schließen, sichtbare Geräte sind unbeschädigt.'],
['Sofort melden und was in die Meldung gehört','Technik','Alle Wohnungen','Sofort melden: Wasser- oder Feuchtigkeitsschäden, beschädigte Fenster oder Türen, fehlende Schlüssel, defekte Geräte, elektrische Auffälligkeiten, Glasbruch, starke Gerüche oder Schimmelverdacht, fehlende oder beschädigte Ausstattung, zurückgelassene Wertgegenstände, starke ungewöhnliche Verschmutzung. Eine Meldung enthält Wohnung und Raum, eine kurze Beschreibung, ein Foto wenn sinnvoll, den Zeitpunkt, die Dringlichkeit und bereits getroffene sichere Maßnahmen. Nicht erlaubt: Schäden verdecken, defekte Geräte weiterbenutzen, unbekannte Mittel mischen, Fundstücke entsorgen, vollständige Zugangscodes offen notieren.'],
['Wohnung nicht freigeben bei','Housekeeping','Alle Wohnungen','Nicht freigeben bei Wasserleck oder Feuchtigkeit, Strom-, Gas- oder Sicherheitsproblem, beschädigtem Fenster oder nicht sicher schließender Tür, fehlender oder stark verschmutzter Bettwäsche, nicht behobenem WC- oder Duschenproblem, erheblicher Geruchsbelastung, fehlendem kritischem Inventar oder einem Zugangsproblem. In diesen Fällen die Wohnung als nicht fertig melden und die zuständige Person informieren. Die Reinigungskraft gibt eine Wohnung nie eigenmächtig frei, wenn ein kritischer Mangel besteht.'],
['Kücheninventar und Mengenregel','Housekeeping','Alle Wohnungen','Nach der wohnungsspezifischen Inventarliste prüfen: Teller und Schüsseln, Tassen und Gläser, Besteck, Töpfe und Pfannen, Schneidebretter, Messer, Küchenhelfer, Sieb, Dosen- und Flaschenöffner, Kaffeemaschine mit Zubehör, Wasserkocher und Toaster. Als Startstandard gilt, solange nichts anderes festgelegt ist: maximale Belegung plus zwei zusätzliche Stück pro Grundkategorie bei Tellern, Gläsern, Tassen und Besteck. Ist eine Menge nicht festgelegt, bei Lena nachfragen statt zu raten.']
];
const entries:Entry[]=content.map((r,i)=>({id:`e${i+1}`,title:r[0],category:r[1],unit:r[2],body:r[3],roles:r[1]==='Verwaltung'?['owner','staff']:all,version:1,verified:today,season:'Sommer 2026',due:i===6?'2026-01-01':new Date(Date.now()+30*86400000).toISOString().slice(0,10),owner:'Lena',history:[]}));
const standardDefs=[
['st1','Schlafzimmer bezugsfertig','Schlafzimmer','Alle Wohnungen','p1','p1-s1',['Bett vollständig bezogen, Decke glatt aufgelegt','Zwei aufgeschüttelte Kissen pro Doppelbett','Papierkorb sichtbar leer','Zwei gefaltete Handtücher bereitgelegt','Nachttische frei von Gegenständen der Vorgäste','Vorhänge geöffnet, Fensterbank frei']],
['st2','Bad bezugsfertig','Bad','Alle Wohnungen','p1','p1-s2',['Ersatzrolle Toilettenpapier sichtbar bereitgestellt','Handtücher und Duschtuch aufgehängt','Spiegel und Armaturen streifenfrei','Duschwanne frei von Haaren und Rückständen','Papierkorb leer, neuer Beutel eingesetzt','Seife oder Spender gefüllt']],
['st3','Küche im Zirbennest','Küche','Zirbennest','p1','p1-s3',['Kapselbehälter der Kaffeemaschine geleert','Tropfschale sauber, Wassertank gefüllt','Spüle trocken, keine Rückstände','Geschirr vollständig und eingeräumt','Arbeitsfläche frei und abgewischt','Mülleimer leer']]
] as const;
const standards:Standard[]=standardDefs.map(d=>({id:d[0],title:d[1],room:d[2],unit:d[3],roles:all,processId:d[4],stepId:d[5],checklist:[...d[6]],version:1,updated:today,owner:'Lena',history:[]}));
const defs=[['p1','Gästewechsel & Reinigung','Eine Wohnung bereit für die nächsten Gäste machen.','Housekeeping',['e9','e1','e6','e5','e8','e12']],['p2','Anreise & Schlüsselübergabe','Alles für eine entspannte Ankunft vorbereiten.','Anreise',['e12','e16','e2']],['p3','Bereit für die neue Saison','Material, Ausstattung und Wissen gemeinsam prüfen.','Saison',['e15','e9','e16','e12']],['p4','Technische Störung','Sicher reagieren, dokumentieren und Hilfe organisieren.','Technik',['e10','e9','e16']]] as const;
const reinigung=[
['Auftrag und Material vorbereiten','Reinigungsart prüfen: Abreise-, Zwischen-, Grund- oder Sonderreinigung. Wohnung und geplante Belegung prüfen, besondere Hinweise lesen. Bettwäsche, Handtücher und Bademäntel bereitstellen. Tücher und Moppbezüge nach Farbsystem richten. Reinigungsmittel, Handschuhe und Bürsten bereitstellen. Müllbeutel für das gültige Trennsystem mitnehmen. Toilettenpapier, Handseife und Küchen-Verbrauchsmaterial prüfen. Vollständige Zugangscodes werden nie offen notiert.',['e18','e19']],
['Wohnung betreten und Erstkontrolle','Nach betrieblicher Regel Zugang nehmen und prüfen, ob noch jemand da ist. Kurz lüften, sofern erlaubt und sicher. Sichtbare Schäden und starke Verschmutzungen feststellen. Fundstücke sichern und melden, niemals wegwerfen. Auf ungewöhnliche Gerüche, Feuchtigkeit und Wasserstellen achten. Fenster, Fenstergriffe und Türen kurz prüfen. Kritische Auffälligkeiten sofort melden, bevor es weitergeht.',['e21','e9']],
['Spülmaschine sofort starten','Benutztes Geschirr aus allen Räumen einsammeln und grobe Speisereste entfernen. Maschine richtig beladen und prüfen, ob alles spülmaschinengeeignet ist. Spülmittel oder Tab einlegen und das vorgesehene Programm starten. Bei einer Störung die zuständige Person informieren und das Gerät nicht weiterbenutzen. Ausgeräumt wird später im Küchenschritt.',['e18']],
['Sammelrunde für Wäsche, Müll und Fundstücke','Bettwäsche aus beiden Schlafzimmern entfernen, Kissen, Decken und Matratzenschoner prüfen. Benutzte Handtücher, Bademäntel und Badvorleger einsammeln und auf Flecken, Schäden und Geruch prüfen. Stark verschmutzte Wäsche getrennt sammeln. Mülleimer leeren und nach den örtlichen Kategorien trennen. Fundstücke niemals mit dem Müll entsorgen. Danach ist in keinem Raum mehr gebrauchte Wäsche, Abfall oder benutztes Geschirr.',['e18','e1']],
['Waschmaschine starten','Wäsche nach der betrieblichen Wäschevorgabe sortieren, Bademäntel nach Material- und Farbvorgabe berücksichtigen. Maschine nicht überladen. Freigegebenes Programm und Waschmittel verwenden. Welches Programm und welches Mittel gelten, ist in dieser Demo noch nicht festgelegt – dann bei Lena nachfragen statt raten. Läuft die Wäsche zum Schichtende noch, bei der Übergabe dokumentieren.',['e1']],
['Badezimmer und WCs vorbereiten','Dusche, Waschbecken und Bad-WC mit dem vorgesehenen Mittel vorbereiten, ebenso Waschbecken und WC im separaten WC. Die Mittel wirken ein, während andere Räume gereinigt werden. Einwirkzeiten beachten, Reinigungsmittel niemals mischen, vorgesehene Handschuhe verwenden. Bei unbekannten Produkten nicht improvisieren, sondern nachfragen.',['e6','e18']],
['Schlafzimmer 1 reinigen und Bett herstellen','Mit blauen Materialien arbeiten. Oberflächen von oben nach unten reinigen, Lampen, Ablagen und Nachttische. Schränke und Schubladen auf Fundstücke prüfen, unter dem Bett nachsehen. Matratze, Matratzenschoner und Bettgestell kontrollieren. Türen, Griffe und Lichtschalter reinigen, Fensterbank und Fensterflächen kontrollieren. Passende saubere Bettwäsche aufziehen, Kissen und Decke ordentlich platzieren. Der Boden kommt später. Fertig heißt: Bettwäsche sauber, trocken, passend und faltenarm, keine Haare, Flecken oder Gegenstände sichtbar, Oberflächen staubfrei.',['e17','e1']],
['Schlafzimmer 2 reinigen und Bett herstellen','Gleicher Ablauf wie in Schlafzimmer 1, ebenfalls mit blauen Materialien. Besonders auf Unterschiede achten: richtige Bettgröße und passende Wäsche verwenden, abweichende Ausstattung oder Möblierung beachten. Fenster, Türen, Schränke und Bettbereich kontrollieren. Beide Schlafzimmer entsprechen demselben Hausstandard, sofern für die Wohnung nichts anderes dokumentiert ist.',['e17','e1']],
['Wohn- und Essbereich reinigen','Mit blauen Materialien arbeiten. Oberflächen und Ablagen, Esstisch und Stühle reinigen. Sofa und sichtbare Polster kontrollieren, unter und zwischen den Sitzmöbeln nachsehen. Fernbedienungen, Lampen und sichtbare Ausstattung kontrollieren. Türen, Griffe und Lichtschalter reinigen. Fenster, Fensterbänke und Glasflächen prüfen. Möbel und Dekoration nach Hausstandard ordnen, Fehlendes oder Beschädigtes melden.',['e17']],
['Küche reinigen und auffüllen','Mit grünen Materialien arbeiten, niemals rote oder gelbe Tücher in der Küche. Spülmaschine kontrollieren, nach Programmende ausräumen und das Geschirr auf Sauberkeit prüfen. Arbeitsflächen reinigen, Spüle und Armatur reinigen und trocken nachwischen. Kochfeld, Küchenfronten und Griffe reinigen, Tisch und Stühle abwischen. Backofen, Mikrowelle, Kühlschrank und Tiefkühlfach kontrollieren. Küchenabfall leeren und Behälter bei Bedarf auswischen. Inventar nach Liste prüfen und Verbrauchsmaterial auffüllen.',['e17','e23','e5']],
['Badezimmer reinigen und auffüllen','Gelbe Materialien für Dusche, Waschbecken, Spiegel und Ablagen. Dusche und Duschflächen reinigen, Duschwand oder Vorhang kontrollieren, Armaturen, Waschbecken und Spiegel reinigen. Sichtbare Kalk- und Wasserflecken entfernen, Abfluss prüfen. Für das WC ein frisches rotes Tuch nehmen und WC innen und außen, die Umgebung sowie Bürste und Halterung reinigen. Auffüllen: Toilettenpapier am Halter, Reservepapier nach Hausstandard, Handseife, Handtücher und Badvorleger. Fertig heißt: sichtbar sauber, Flächen trocken, keine Haare, Flecken, Kalkreste oder Gerüche.',['e17','e6']],
['Separates WC reinigen und auffüllen','Ein frisches rotes Tuch verwenden, nicht das aus dem Bad-WC. Waschbecken, Armatur und Spiegel reinigen. WC innen und außen reinigen, Bürste und Halterung kontrollieren. Boden und unmittelbaren WC-Bereich reinigen. Toilettenpapier und Reservepapier bereitstellen, Handseife auffüllen, Handtuch bereitstellen. Fertig heißt: sauber, trocken, geruchsfrei und vollständig ausgestattet.',['e17']],
['Fenster, Türen und Terrasse kontrollieren','Fensterscheiben auf sichtbare Flecken prüfen, Fensterbänke mit blauem Tuch reinigen, Rahmen und Griffe kontrollieren, Spinnweben entfernen. Prüfen, ob die Fenster nach Hausstandard geschlossen sind; Kondenswasser oder Feuchtigkeit melden. Eingangstür und Innentüren kontrollieren, Türgriffe und Lichtschalter reinigen, Schlösser auf Schäden und korrektes Schließen prüfen. Balkon oder Terrasse: Flächen kontrollieren, Möbel reinigen und vollständig aufstellen, Müll entfernen, Geländer und Glasflächen prüfen. Eine vollständige Fensterreinigung ist ein eigener Auftrag und nicht Teil der Abreisereinigung.',['e17','e7']],
['Böden reinigen','Immer zuletzt, erst nach allen Arbeiten an Oberflächen, Möbeln, Küche, Bad und WC. Groben Schmutz entfernen und mit dem Raum beginnen, der am weitesten vom Ausgang entfernt ist. Moppbezug jeweils in der Farbe des Raums: Schlafzimmer und Wohnbereich blau, Küche grün, Bad gelb, WC-Bereiche rot. In Richtung Ausgang arbeiten und gereinigte Böden möglichst nicht mehr betreten. Nasse Böden trocknen lassen und kenntlich machen.',['e17','e18']],
['Ausstattung abschließend auffüllen','Schlafzimmer: Bettwäsche sauber und vorhanden, Kissen und Decken vollständig, gebuchte Zusatzausstattung da. Bad und WC: Toilettenpapier, Reservepapier, Handseife, Handtücher, Badvorleger und Bademäntel, sofern vorgesehen. Küche: Geschirr und Utensilien vollständig, Geschirrtücher, Spülmittel, Tabs, Küchenpapier und Müllbeutel. Bademäntel auf sauber, trocken, fleckenfrei und geruchsfrei prüfen, falten oder aufhängen und am festgelegten Platz bereitstellen. Anzahl nach Belegung kontrollieren.',['e20','e23']],
['Mülltrennung und Entsorgung','Alle Abfalleimer leeren und nach dem gültigen örtlichen System trennen. Behälter bei Bedarf auswischen und neue Beutel einsetzen. Restmüll, Papier, Glas, Verpackungen und weitere Kategorien getrennt entsorgen und zur vorgesehenen Sammelstelle bringen. Trennhinweise prüfen, falsch oder gefährlich entsorgte Gegenstände melden. Die verbindlichen Kategorien und der Ort der Sammelstelle sind in dieser Demo noch nicht festgelegt – im Zweifel nachfragen.',['e21']],
['Raum-für-Raum-Endkontrolle','Jeden Raum einmal durchgehen. Schlafzimmer: Bett frisch und ordentlich bezogen, keine Haare oder Gegenstände, Oberflächen sauber, Schränke geprüft, Fenster und Lichtschalter kontrolliert, Ausstattung vollständig. Wohn- und Essbereich: Möbel und Flächen sauber, Sitzmöbel kontrolliert, Glasflächen geprüft, Fernbedienungen vorhanden. Küche: Spülmaschine ausgeräumt, Inventar sauber und vollständig, Flächen und Spüle sauber, Geräte und Kühlschrank kontrolliert, Verbrauchsmaterial aufgefüllt. Bad und separates WC: alles sauber und trocken, Papier, Seife und Handtücher vorhanden, keine Schäden oder Gerüche. Außen: Fenstercheck erledigt, Türen kontrolliert, Terrasse geordnet, nichts Beschädigtes ungemeldet.',['e20']],
['Gebrauchte Materialien entfernen','Gebrauchte Reinigungstücher aus der Wohnung entfernen, Moppbezüge in den vorgesehenen Wäschesack geben. Saubere und gebrauchte Materialien getrennt halten. Reinigungsmittel und Arbeitsmittel mitnehmen. Stark verschmutzte oder beschädigte Materialien aussortieren. Gebrauchte Tücher nie zurück in die saubere Materialbox legen. Die Wohnung wird ohne Housekeeping-Material zurückgelassen.',['e19']],
['Freigabe und Übergabe','Freigeben, wenn alle Pflichtpunkte erfüllt sind, keine kritische Abweichung offen ist, die Wohnung vollständig ausgestattet ist, Schäden und Fehlmengen dokumentiert wurden und die Endkontrolle erledigt ist. Nicht freigeben bei Wasserleck, Strom- oder Sicherheitsproblem, beschädigtem Fenster oder unsicher schließender Tür, fehlender oder verschmutzter Bettwäsche, ungelöstem WC- oder Duschenproblem, starker Geruchsbelastung, fehlendem kritischem Inventar oder Zugangsproblem. Zur Übergabe gehören: fertig oder nicht fertig, offene Schäden, fehlende Ausstattung, laufende Wasch- oder Trockenmaschine, notwendige Nacharbeit sowie zuständige Person und Dringlichkeit.',['e22','e20','e21']]
] as const;
const abreise:Process={id:'p5',title:'Abreisereinigung Schritt für Schritt',description:'Der vollständige Hausablauf in 19 Schritten, vom Material bis zur Freigabe.',category:'Housekeeping',roles:all,version:1,steps:reinigung.map((r,i)=>({id:`p5-s${i}`,title:r[0],body:r[1],entryIds:[...r[2]]}))};
const processes:Process[]=defs.map(d=>({id:d[0],title:d[1],description:d[2],category:d[3],roles:d[0]==='p2'?['owner','staff']:all,version:1,steps:d[4].map((id,i)=>({id:`${d[0]}-s${i}`,title:entries.find(e=>e.id===id)!.title,body:entries.find(e=>e.id===id)!.body,entryIds:[id]}))}));
return {entries,processes:[...processes,abreise],standards,inspections:[],contributions:[{id:'c-seed',title:'Fenstergriff wurde repariert',body:'Der Fenstergriff im Schlafzimmer von Alpenblick wurde heute ausgetauscht. Er lässt sich wieder normal bedienen. Bitte die alte Warnung nach Kontrolle aktualisieren.',entryId:'e7',unit:'Alpenblick',author:'cleaner',status:'open',created:today},{id:'c-gap',title:'Wo stehen Ersatzglühbirnen?',body:'Bei der letzten Reinigung war der Lagerort unklar. Bitte ergänzen.',unit:'Alle Wohnungen',author:'staff',status:'open',created:today}],runs:[],ledger:[{id:'seed-points',role:'cleaner',points:10,reason:'Hilfreichen Hinweis zur Wäschesortierung bestätigt',date:today}],rewards:[],checks:[],handover:{notes:'Fenstergriff Alpenblick: Reparatur prüfen. Lagerort für Ersatzglühbirnen ergänzen.',summary:'',status:'draft',date:today},season:'Sommer 2026',settings:{calls:0,day:today}};
}
