import {State,Entry,Process,Role} from './types';
export function seed():State {
const today=new Date().toISOString().slice(0,10); const all:Role[]=['owner','staff','cleaner'];
const content=[
['Wäsche für den Gästewechsel','Housekeeping','Alle Wohnungen','Pro gebuchter Person ein großes und ein kleines Handtuch bereitlegen. Bettwäsche vollständig wechseln. Saubere Wäsche liegt im beschrifteten Schrank im Wirtschaftsraum. Benutzte Wäsche kommt in den grauen Sack.'],
['Schlüsselübergabe Alpenblick','Anreise','Alpenblick','Die Schlüsselübergabe erfolgt persönlich durch Lena. Bei später Anreise Lena kontaktieren und den vereinbarten Ablauf bestätigen lassen. Zugangscodes stehen aus Sicherheitsgründen nicht in dieser Demo.'],
['Schlüsselübergabe Zirbennest','Anreise','Zirbennest','Die betreibende Person übergibt den Schlüssel am Haupteingang. Vor Anreise Ankunftszeit und erreichbare Ansprechperson bestätigen.'],
['Schlüsselübergabe Talruhe','Anreise','Talruhe','Schlüssel bei der vereinbarten Übergabe im Büro abholen. Bei abweichender Ankunft Lena kontaktieren.'],
['Kaffeemaschine im Zirbennest','Housekeeping','Zirbennest','Die Kapselmaschine ausschalten und abkühlen lassen. Kapselbehälter leeren, Tropfschale reinigen und Wassertank mit frischem Wasser füllen. Keine Entkalkung ohne die Geräteanleitung starten.'],
['Bad und Oberflächen','Housekeeping','Alle Wohnungen','Reinigungsmittel ausschließlich nach Etikett verwenden, nicht mischen. Separate Tücher für Bad und Küche verwenden. Armaturen trocknen und Spiegel auf Streifen prüfen.'],
['Fenstergriff im Alpenblick','Technik','Alpenblick','Der Fenstergriff im Schlafzimmer hakt. Nicht mit Gewalt drehen. Bei Problemen Fenster sichern, sofern gefahrlos möglich, und Lena informieren. Eine Reparatur ist bereits angefragt.'],
['Fundgegenstände','Housekeeping','Alle Wohnungen','Fundsachen beschriften: Wohnung, Funddatum und Fundort. Im verschlossenen Fach im Büro abgeben und die Betreiberin informieren. Keine Fotos persönlicher Dokumente hochladen.'],
['Schaden oder Störung melden','Technik','Alle Wohnungen','Wohnung, betroffenes Gerät und beobachtetes Problem notieren, wenn sicher möglich ein Foto aufnehmen. Lena über den betrieblich vereinbarten Kontaktweg informieren. Keine elektrischen Geräte öffnen.'],
['Akute Gefahr','Technik','Alle Wohnungen','Bei akuter Gefahr Arbeiten abbrechen, sich und andere in Sicherheit bringen und den örtlichen Notruf verständigen. Keine eigene Reparatur versuchen. Anschließend Betreiberin informieren, sobald dies sicher möglich ist.'],
['WLAN in Talruhe','Technik','Talruhe','Die WLAN-Informationen befinden sich in der physischen Gästemappe. Bei Verbindungsproblemen zuerst prüfen, ob mehrere Geräte betroffen sind. Router nicht eigenständig zurücksetzen; Lena informieren.'],
['Anreise vorbereiten','Anreise','Alle Wohnungen','Bestätigte Ankunftszeit und Personenzahl prüfen. Reinigungsabschluss bestätigen lassen. Schlüsselübergabe passend zur Wohnung organisieren. Keine persönlichen Gästedaten in den Buddy eingeben.'],
['Anzahlung und Restzahlung','Verwaltung','Alle Wohnungen','Für diesen fiktiven Betrieb gilt: Den vereinbarten Zahlungsplan in der Buchungsbestätigung prüfen. Zahlungseingänge im Buchungssystem abgleichen. Abweichungen an Lena geben. Der Buddy führt keine Zahlungen aus.'],
['Gästekarte ausstellen','Verwaltung','Alle Wohnungen','Das zuständige regionale Gästekartenportal und dessen aktuelle Anleitung verwenden. Berechtigung und erforderliche Angaben dort prüfen. Diese Demo kennt keine verbindlichen regionalen Ausstellungsregeln.'],
['Saisonstart: Material prüfen','Saison','Alle Wohnungen','Bettwäsche, Handtücher und freigegebene Reinigungsmittel zählen. Fehlendes Material melden. Inventar und bekannte Schäden mit der letzten Übergabe abgleichen.'],
['Kontakt und Zuständigkeit','Anreise','Alle Wohnungen','Lena ist für Freigaben, Anreise und technische Eskalation zuständig. Jonas koordiniert Gästewechsel, Mira übernimmt Reinigung. Dies sind fiktive Personen; echte Kontaktdaten sind noch zu hinterlegen.']
];
const entries:Entry[]=content.map((r,i)=>({id:`e${i+1}`,title:r[0],category:r[1],unit:r[2],body:r[3],roles:r[1]==='Verwaltung'?['owner','staff']:all,version:1,verified:today,season:'Sommer 2026',due:i===6?'2026-01-01':new Date(Date.now()+30*86400000).toISOString().slice(0,10),owner:'Lena',history:[]}));
const defs=[['p1','Gästewechsel & Reinigung','Eine Wohnung bereit für die nächsten Gäste machen.','Housekeeping',['e9','e1','e6','e5','e8','e12']],['p2','Anreise & Schlüsselübergabe','Alles für eine entspannte Ankunft vorbereiten.','Anreise',['e12','e16','e2']],['p3','Bereit für die neue Saison','Material, Ausstattung und Wissen gemeinsam prüfen.','Saison',['e15','e9','e16','e12']],['p4','Technische Störung','Sicher reagieren, dokumentieren und Hilfe organisieren.','Technik',['e10','e9','e16']]] as const;
const processes:Process[]=defs.map(d=>({id:d[0],title:d[1],description:d[2],category:d[3],roles:d[0]==='p2'?['owner','staff']:all,version:1,steps:d[4].map((id,i)=>({id:`${d[0]}-s${i}`,title:entries.find(e=>e.id===id)!.title,body:entries.find(e=>e.id===id)!.body,entryIds:[id]}))}));
return {entries,processes,contributions:[{id:'c-seed',title:'Fenstergriff wurde repariert',body:'Der Fenstergriff im Schlafzimmer von Alpenblick wurde heute ausgetauscht. Er lässt sich wieder normal bedienen. Bitte die alte Warnung nach Kontrolle aktualisieren.',entryId:'e7',unit:'Alpenblick',author:'cleaner',status:'open',created:today},{id:'c-gap',title:'Wo stehen Ersatzglühbirnen?',body:'Bei der letzten Reinigung war der Lagerort unklar. Bitte ergänzen.',unit:'Alle Wohnungen',author:'staff',status:'open',created:today}],runs:[],ledger:[{id:'seed-points',role:'cleaner',points:10,reason:'Hilfreichen Hinweis zur Wäschesortierung bestätigt',date:today}],rewards:[],checks:[],handover:{notes:'Fenstergriff Alpenblick: Reparatur prüfen. Lagerort für Ersatzglühbirnen ergänzen.',summary:'',status:'draft',date:today},season:'Sommer 2026',settings:{calls:0,day:today}};
}
