import {cookies} from 'next/headers';
import {randomUUID,createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import path from 'node:path';
import {seed} from './seed';import {State,Role} from './types';
const dir=path.join(process.cwd(),'.data');
const remote=!!process.env.SUPABASE_URL&&!!process.env.SUPABASE_SERVICE_ROLE_KEY;
export async function identity(){const c=await cookies();let id=c.get('sw-session')?.value;if(!id||!/^\w{8}-[\w-]{27,40}$/.test(id)){id=randomUUID();c.set('sw-session',id,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:60*60*24*30,path:'/'});}const value=c.get('sw-role')?.value;const role:Role=value==='staff'||value==='cleaner'?value:'owner';return {id,role};}
export async function roleCookie(role:Role){if(!['owner','staff','cleaner'].includes(role))throw Error('Ungültige Rolle.');(await cookies()).set('sw-role',role,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'});}
function headers(){return {'apikey':process.env.SUPABASE_SERVICE_ROLE_KEY!,'Authorization':`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json'};}
async function request(url:string,options:RequestInit={}){const r=await fetch(`${process.env.SUPABASE_URL}/rest/v1/${url}`,{...options,headers:{...headers(),...options.headers},cache:'no-store'});if(!r.ok)throw Error('Datenbank nicht erreichbar. Bitte Supabase-Einrichtung prüfen.');return r;}
type RecordState={data:State;version:number};
async function read(id:string):Promise<RecordState>{if(remote){let r=await request(`demo_workspaces?id=eq.${id}&select=data,version`);let rows=await r.json();if(!rows.length){await request('demo_workspaces?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({id,data:seed(),version:0})});rows=await(await request(`demo_workspaces?id=eq.${id}&select=data,version`)).json();}return rows[0];}if(process.env.VERCEL)throw Error('Für das Deployment bitte Supabase konfigurieren.');await mkdir(dir,{recursive:true});try{return JSON.parse(await readFile(path.join(dir,`${id}.json`),'utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;return {data:seed(),version:0};}}
let queue=Promise.resolve();
export async function transaction<T>(id:string,fn:(s:State)=>T|Promise<T>):Promise<T>{let release!:()=>void;const previous=queue;queue=new Promise<void>(r=>release=r);await previous;try{const record=await read(id);const value=await fn(record.data);if(remote){const r=await request(`demo_workspaces?id=eq.${id}&version=eq.${record.version}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({data:record.data,version:record.version+1})});if(!(await r.json()).length)throw Error('Parallel geändert. Bitte Aktion erneut ausführen.');}else{const file=path.join(dir,`${id}.json`),tmp=`${file}.${randomUUID()}.tmp`;await writeFile(tmp,JSON.stringify({data:record.data,version:record.version+1}));await rename(tmp,file);}return value;}finally{release();}}
async function encryptionKey(){let secret=process.env.ENCRYPTION_SECRET;if(!secret){if(process.env.VERCEL)throw Error('ENCRYPTION_SECRET fehlt.');await mkdir(dir,{recursive:true});const p=path.join(dir,'.key');try{secret=await readFile(p,'utf8');}catch{secret=randomBytes(32).toString('hex');await writeFile(p,secret,{mode:0o600});}}return createHash('sha256').update(secret).digest();}
export async function encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',await encryptionKey(),iv);const out=Buffer.concat([cipher.update(value),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),out]).toString('base64');}
export async function apiKey(s:State){if(s.settings.keyCipher){const raw=Buffer.from(s.settings.keyCipher,'base64'),d=createDecipheriv('aes-256-gcm',await encryptionKey(),raw.subarray(0,12));d.setAuthTag(raw.subarray(12,28));return Buffer.concat([d.update(raw.subarray(28)),d.final()]).toString();}if(!process.env.VERCEL||process.env.ALLOW_SHARED_DEMO_KEY==='true')return process.env.MISTRAL_API_KEY;}
export function guard(req:Request){const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==(req.headers.get('host')||new URL(req.url).host))throw Error('Anfrage von fremder Website abgelehnt.');}
export async function saveFile(id:string,file:File){const fileId=randomUUID();const bytes=Buffer.from(await file.arrayBuffer());if(remote){const r=await fetch(`${process.env.SUPABASE_URL}/storage/v1/object/attachments/${id}/${fileId}`,{method:'POST',headers:{...headers(),'Content-Type':file.type||'application/octet-stream'},body:bytes});if(!r.ok)throw Error('Datei konnte nicht gespeichert werden.');}else{await mkdir(path.join(dir,'files',id),{recursive:true});await writeFile(path.join(dir,'files',id,fileId),bytes);}return fileId;}
export async function loadFile(id:string,fileId:string){if(!/^[\w-]{36}$/.test(fileId))throw Error('Datei fehlt.');if(remote){const r=await fetch(`${process.env.SUPABASE_URL}/storage/v1/object/attachments/${id}/${fileId}`,{headers:headers()});if(!r.ok)throw Error('Datei fehlt.');return Buffer.from(await r.arrayBuffer());}return readFile(path.join(dir,'files',id,fileId));}
